name: easy_date_time_example
description: Examples for easy_date_time package
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  dio: ^5.9.0
  easy_date_time:
    path: ../
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  retrofit: ^4.9.2

dev_dependencies:
  build_runner: ^2.10.5
  freezed: ^3.2.4
  json_serializable: ^6.11.4
  lints: ^6.0.0
  retrofit_generator: ^10.2.1
