name: easy_date_time
description: A drop-in DateTime replacement with IANA timezone support. Preserves original time values when parsing.
version: 0.9.1
homepage: https://github.com/MasterHiei/easy_date_time
repository: https://github.com/MasterHiei/easy_date_time
issue_tracker: https://github.com/MasterHiei/easy_date_time/issues
documentation: https://github.com/MasterHiei/easy_date_time/blob/main/README.md

topics:
  - datetime
  - timezone
  - calendar
  - formatting
  - utils

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  timezone: ">=0.9.4 <0.11.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
